const quotes = [
    "A Post-It note could sense danger better than this guy.",
    "Abstract expressionism, it's what's hot!",
    "Ah, beautiful downtown Hugo!",
    "Ah, it's just some kids down there.",
    "All the names are Russian for Alan Smithee.",
    "America is leaning on cheese!",
    "An American Werewolf in Traffic.",
    "And starring Technicolor as himself.",
    "And the answer is…dull surprise!",
    "And, with that cryptic comment, I'm going to bed.",
    "Antigravity! It's not just for breakfast anymore!",
    "Any fruit to declare?",
    "Any moment now, unspeakable horror! Trust me!",
    "Are you ready for some football?",
    "Ask me about my extra chromosome!",
    "Bad movie? You're soaking in it!",
    "BANG!",
    "Because in space, no one can smell your breath.",
    "Capsule!",
    "Cavorting really makes you lose your electrolytes.",
    "Cheating is bad. Richard Basehart is good.",
    "Chili peppers burn my gut.",
    "C'mon, I just teleported here! It's impressive!",
    "Day 12: The expedition turns whiny.",
    "Death by snicker-snag…",
    "DEEEEEEEEEEP HUUUURRRTINGGGG!!!",
    "Designed by I.M. Pei, built by Jim Varney.",
    "Did I mention that I cried?",
    "Did someone tape a dinner roll to his chin?",
    "Do I please you? Do you find me pleasing?",
    "Does this bug you? I'm not touching you.",
    "Does this really merit the tender music?",
    "Eleven dollars went a long way back then.",
    "Enjoy our hockey stick actors.",
    "Enter the nightmare-fueled world",
    "Even his name says, \"Is that a beer?\"",
    "Even the A-V Club laughs at these guys.",
    "Even the soundtrack is making coffee!",
    "Every frame of this movie looks like someone's last known photograph.",
    "Existential void where prohibited.",
    "Expressing individualism is just plain wrong!",
    "Filmed in Vermont, the other, smaller Wisconsin.",
    "Filmed in Wedgie-Vision.",
    "Fishpicker!",
    "Flame-broiled, deep-fried crime against nature",
    "Frolicking has never been so depressing.",
    "Go bingle your bongle!",
    "Hahahahahahahahaha — YOU'RE STUCK HERE!!",
    "Have some sun, little friend.",
    "He enjoys pantaloons more than he should.",
    "He hit Big Jake!",
    "He tampered in God's domain.",
    "He tried to kill me with a forklift!",
    "He’s Deezening!",
    "Here, drink this. It'll make you feel American.",
    "Hi, honey, I'm smooth!",
    "Hi-Keeba!",
    "How much Keefe is in this movie anyway?",
    "I command you to shake that money-maker!",
    "I have my doubts that this movie is actually \"starring\" anybody.",
    "I never thought the end of the world would be so annoying.",
    "I saw it with my own hair!",
    "I think this movie just broke the goofy-meter.",
    "I want to decide who lives and who dies!",
    "I want you to carry on the family haircut.",
    "I won a parking ticket!",
    "Is it Sampo yet?",
    "Is science supposed to smell like banana creme?",
    "It's after the apocalypse! Nobody's hiring!",
    "It's called EVIL, kid.",
    "It's more like Jean Claude Gosh Darn.",
    "It's the feel-good film of the Cold War era!",
    "It's the amazing technicolor cheese wedge!",
    "I'm a Grimald warrior!",
    "I'm huge!",
    "I'm not forgetting YOU, Danny from the last movie.",
    "I'm the god, I'M THE GOD!",
    "Kids worship the darnedest things!",
    "Knew your father, I did!",
    "Live fast, die young, and leave a fat, bloated, ugly corpse.",
    "Look, if I want my opinion I'll beat it out of me!",
    "My reviews have destroyed whole cities!",
    "Now you're Mister Filing Cabinet!",
    "Oh, bite me. It's fun!",
    "Oh, who doesn't own an interociter these days?",
    "Paul! I loved your letter to the Corinthians!",
    "Please slip corpses under the door after ten.",
    "Remember to believe in magic, or I'll kill you.",
    "Rex Dart: Eskimo Spy!",
    "Special effects by Industrial Light and Morons.",
    "Thank God we have radar!",
    "The Duluth Chamber of Commerce bids you adieu.",
    "They just didn't care!",
    "This is the avalanche, ready for me?",
    "This watery manifestation of a vengeful, wrathful God could not've come at a worse time.",
    "Time for go to bed.",
    "Trains are blameless, holy creatures.",
    "Trumpy, you can do magic things!",
    "Try the Fentoozler!",
    "Vintage cars were really popular back then!",
    "Wall-mounted keyboards?  It must be the future!",
    "Watch out for snakes!",
    "We can fix things, we just don't want to!",
    "Well there's your problem - it's pudding!",
    "Werewolves are basically Jackson Browne.",
    "We're getting into a whole weird area here.",
    "We're goin' campin' and you're gonna watch.",
    "What do you WANT from us? We're EVIL. <i>EVIL!</i>",
    "When you want the flavor of bacon in a dip.",
    "Where your in-flight movie is, \"I Don't Care!\"",
    "You are watching the Venetian Blind Channel.",
    "You look at it, I'm bitter.",
    "You sound like a manure salesman with a mouthful of samples.",
    "You're a disgrace to all Kens.",
    "You're not my real father, mister!"
]